local cars = { "adder", "kuruma", "cheetah", "faggio" }

RegisterCommand('textuitesttttt', function()
   exports['g-textui']:showTextUI("textui_test_G", "Five Developments another file", "G")
   Wait(3000)
   exports['g-textui']:hideText("textui_test_G")
   Wait(3000)
   exports['g-textui']:showTextUI("textui_test", "Groot Development", "E")
   Wait(2000)
   exports['g-textui']:hideText("textui_test")
end, false)

-- local G = exports['g-bridgeV2']:GetGroot()
-- RegisterCommand('gadditem', function(source)
--    -- local player = G.GetPlayer(source)
--    -- print("Player Name: ", player.getName())
--    -- print("Player Identifier: ", G.GetIdentifier(source))
--    -- G.ShowNotification(source, "Added Item", "success")
--    G.ShowNotification("Added Item", "success")
-- end, false)
RegisterCommand('testexport', function()
   exports['g-giftcard']:CreateCard(1, 1000, 'cash', 'cash')
end, false)
